### ISSUE TITLE
Power Function 

### ISSUE THREAD

**Issue by nicolau10010** [robotomize/regression-php#6]
Hi, 
On PowerRegressionLine the equation is:
        `$this->equation = sprintf('y = %s + x^%s', round($A, 2), round($B, 2));`

should be like this??
        `$this->equation = sprintf('y = %s * x^%s', round($A, 2), round($B, 2));`
I mean change the (+) for (*)
By the way awsome work.

**Comment by robotomize** [comment]
Thanks, OK, I'll check it out soon.

**Comment by robotomize** [comment]
Yes, you're right, it's a typo, thanks!
